version: "3.8"

networks:
  backend:

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
      context: .
      target: cli
      args:
        PHP_VERSION: '8.2'
    volumes:
      - './:/code'
      - './docker/php/conf.d/:/usr/local/etc/php/conf.d/'
    networks:
      - backend
